name: Deploy to Dev

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DEMODATABRICKSHOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKSDEMOJOBSECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main

      - name: Deploy bundle
        run: databricks bundle deploy -t dev

      - name: Run job
        run: databricks bundle run topics_job -t dev